# If strict_mode is set to 1, the given answer must equal to the expected answer.
# Otherwise expected answer is simply shown after submitting your answer.
strict_mode=0

randomize_questions=1

# -1 - infinite loop until quit (/q)
#  0 - quiz the whole category
# >0 - number of questions. If this number is more than the number of
#      available questions, it will limit to all available questions.
questions_per_quiz=0
